import { afterEach, expect, it } from 'vitest'
import { rm } from 'node:fs/promises'
import { setup, readyBot, until, FakeConnector } from './bot-helpers.js'
const contexts: Awaited<ReturnType<typeof setup>>[] = []
afterEach(async () => { for (const ctx of contexts.splice(0)) { await ctx.service.close(); await rm(ctx.dir, { recursive: true, force: true }) } })
it.skipIf(process.platform === 'win32')('creates B in A’s VM without provisioning and isolates concurrent turns, files and archival', async () => {
  const connector = new FakeConnector(); connector.managed = true
  const ctx = await setup({ connector }); contexts.push(ctx)
  const a = await readyBot(ctx, 'A')
  const before = await ctx.call('vm.list')
  const preview = await ctx.call('bot.setup.preview', { destination: { kind: 'shared-vm', vmId: a.vmId } })
  expect(preview.feasible).toBe(true)
  expect(preview.destination).toMatchObject({ kind: 'shared-vm', existingBots: 1, availableSessions: 1 })
  const op = await ctx.call('bot.setup.start', { idempotencyKey: 'B-setup', previewId: preview.previewId, inventoryRevision: preview.inventoryRevision, name: 'B', confirmations: { destination: true, permissions: true } })
  await until(() => ctx.call('bot.setup.inspect', { operationId: op.id }), o => o.status === 'waiting_user')
  const b = await ctx.call('bot.inspect', { botId: op.botId })
  const bSession = await ctx.call('bot.session.inspect', { botId: b.id }), aSession = await ctx.call('bot.session.inspect', { botId: a.id })
  expect(b.vmId).toBe(a.vmId); expect(aSession.id).not.toBe(bSession.id)
  connector.guest(b.vmId, bSession.id).auth = { state: 'connected', provider: 'codex' }
  await ctx.call('bot.auth.status', { botId: b.id })
  const [ta, tb] = await Promise.all([a, b].map(bot => ctx.call('bot.messages.send', { botId: bot.id, clientMessageId: 'same-key', content: 'parallel' })))
  await until(() => ctx.call('bot.turn.get', { turnId: ta.turn.id }), t => t.status === 'running')
  await until(() => ctx.call('bot.turn.get', { turnId: tb.turn.id }), t => t.status === 'running')
  expect(await ctx.call('vm.list')).toEqual(before)
  expect(ctx.provider.calls.filter(c => c === 'provision')).toHaveLength(1)
  connector.guest(a.vmId, aSession.id).files.set('report.txt', Buffer.from('only A'))
  expect(await ctx.call('bot.files.list', { botId: b.id })).toEqual([])
  await ctx.call('bot.turn.cancel', { turnId: ta.turn.id, expectedRevision: (await ctx.call('bot.turn.get', { turnId: ta.turn.id })).revision })
  await until(() => ctx.call('bot.turn.get', { turnId: ta.turn.id }), t => t.status === 'cancelled')
  expect((await ctx.call('bot.turn.get', { turnId: tb.turn.id })).status).toBe('running')
  await expect(ctx.call('vm.shutdown', { vmId: a.vmId, expectedRevision: before[0].revision, idempotencyKey: 'stop-all' })).rejects.toMatchObject({ code: 'BOT_ACTIVE' })
  const archive = await ctx.call('bot.archive', { botId: a.id, expectedRevision: (await ctx.call('bot.inspect', { botId: a.id })).revision, idempotencyKey: 'archive-A' })
  expect(archive.status).toBe('succeeded')
  expect(connector.stopped).toEqual([aSession.id, aSession.id]) // cancellation, then explicit archival
  expect(connector.guest(b.vmId, bSession.id).alive).toBe(true)
  expect((await ctx.call('bot.turn.get', { turnId: tb.turn.id })).status).toBe('running')
  connector.guest(b.vmId, bSession.id).finish(tb.turn.id)
  await until(() => ctx.call('bot.turn.get', { turnId: tb.turn.id }), t => t.status === 'succeeded')
  await ctx.call('bot.archive', { botId: b.id, expectedRevision: (await ctx.call('bot.inspect', { botId: b.id })).revision, idempotencyKey: 'archive-B' })
  const stopping = await ctx.call('vm.shutdown', { vmId: a.vmId, expectedRevision: (await ctx.call('vm.inspect', { vmId: a.vmId })).revision, idempotencyKey: 'stop-archived' })
  await until(() => ctx.call('operation.get', { operationId: stopping.id }), o => o.status === 'succeeded')
  const removing = await ctx.call('vm.remove', { vmId: a.vmId, expectedRevision: (await ctx.call('vm.inspect', { vmId: a.vmId })).revision, idempotencyKey: 'explicit-purge', deleteData: true })
  await until(() => ctx.call('operation.get', { operationId: removing.id }), o => o.status === 'succeeded')
  expect((await ctx.call('vm.inspect', { vmId: a.vmId })).diskRetained).toBe(false)
  expect((await ctx.call('bot.messages.list', { botId: a.id })).messages).toHaveLength(1)
})
it.skipIf(process.platform === 'win32')('adopts the legacy workspace with a backup and preserves conversation, account, memory and files', async () => {
  const connector = new FakeConnector()
  const ctx = await setup({ connector }); contexts.push(ctx)
  const bot = await readyBot(ctx, 'Existing')
  const legacy = await ctx.call('bot.session.inspect', { botId: bot.id })
  connector.guest(bot.vmId).files.set('kept.txt', Buffer.from('persisted'))
  await ctx.call('bot.memory.upsert', { botId: bot.id, content: 'Keep this preference.' })
  const receipt = await ctx.call('bot.messages.send', { botId: bot.id, clientMessageId: 'history', content: 'first task' })
  await until(() => ctx.call('bot.turn.get', { turnId: receipt.turn.id }), t => t.status === 'running')
  connector.guest(bot.vmId).finish(receipt.turn.id)
  await until(() => ctx.call('bot.turn.get', { turnId: receipt.turn.id }), t => t.status === 'succeeded')
  const history = await ctx.call('bot.messages.list', { botId: bot.id }), memory = await ctx.call('bot.memory.list', { botId: bot.id })
  connector.managed = true
  const request = { botId: bot.id, idempotencyKey: 'adopt', confirmBackup: true, confirmRestart: true }
  const op = await ctx.call('bot.runtime.prepare', request)
  const final = await until(() => ctx.call('bot.operation.get', { operationId: op.id }), o => ['failed', 'succeeded'].includes(o.status))
  expect(final.status, JSON.stringify(final.error)).toBe('succeeded')
  expect(await ctx.call('bot.runtime.prepare', request)).toMatchObject({ id: op.id })
  expect(ctx.provider.backups).toEqual([bot.vmId])
  expect(ctx.provider.calls.filter(c => c === 'provision')).toHaveLength(1)
  expect(await ctx.call('bot.session.inspect', { botId: bot.id })).toMatchObject({ id: legacy.id, transport: 'managed', vmId: bot.vmId })
  expect(await ctx.call('bot.messages.list', { botId: bot.id })).toEqual(history)
  expect(await ctx.call('bot.memory.list', { botId: bot.id })).toEqual(memory)
  expect(await ctx.call('bot.auth.status', { botId: bot.id })).toMatchObject({ state: 'connected' })
  expect(await ctx.call('bot.files.list', { botId: bot.id })).toMatchObject([{ path: 'kept.txt', size: 9 }])
})
