import assert from 'node:assert/strict'
import { test } from 'node:test'
import { readFile, readdir } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const read = (relative) => readFile(path.join(root, relative), 'utf8')

test('a routine can only become executable through a preview a person confirmed', async () => {
  const rpc = await read('packages/host-protocol/src/routine-rpc.ts')
  // There is no endpoint that activates, updates or schedules without a preview.
  assert.doesNotMatch(rpc, /'routine\.(create|update|schedule|start)'/)
  assert.match(rpc, /'routine\.preview'/)
  assert.match(rpc, /'routine\.activate'/)
  assert.match(rpc, /confirmSchedule: z\.literal\(true\)/)
  const service = await read('packages/host-core/src/routines/service.ts')
  // Activation revalidates both the fingerprint and the identity of the target.
  assert.match(service, /ROUTINE_PREVIEW_EXPIRED/)
  assert.match(service, /ROUTINE_PREVIEW_MISMATCH/)
  assert.match(service, /target\.version !== stored\.targetVersion/)
})

test('a model can suggest a routine and nothing more', async () => {
  const runtime = await read('packages/host-protocol/src/routine-runtime.ts')
  assert.match(runtime, /ROUTINE_METHODS = \['routine_propose', 'routine_proposal_status'\]/)
  // No activation, no edit, no run, no target selection anywhere in the private lane.
  assert.doesNotMatch(runtime, /routine_activate|routine_run|routine_delete|targetBotId|teamId/)
  const proposals = await read('packages/host-core/src/routines/proposals.ts')
  // A scheduled occurrence, a delegated worker and a continuation may not propose at all.
  assert.match(proposals, /programada não pode criar novas rotinas/)
  assert.match(proposals, /coordination/)
  const client = await read('apps/bot-runtime/src/routines/client.ts')
  // The only way out is the Host channel: no shell, no HTTP, no administrative RPC.
  assert.doesNotMatch(client, /fetch\(|http:\/\/|https:\/\/|child_process|exec\(|spawn\(/)
  for (const file of await readdir(path.join(root, 'apps/bot-runtime/src/routines'))) assert.match(file, /\.ts$/)
})

test('routine proposals travel on their own bounded lane of the private channel', async () => {
  const session = await read('apps/bot-runtime/src/control/session.ts')
  assert.match(session, /routine\.request/)
  assert.match(session, /routine\.response/)
  // One at a time, so writing a card cannot starve cancellation, leases or the live screen.
  assert.match(session, /this\.routineRequests\.size >= 1/)
  const host = await read('packages/host-core/src/guest/session.ts')
  assert.match(host, /this\.routinePending >= 1/)
})

test('an approval fixes a ceiling and the runtime intersects instead of replacing it', async () => {
  const supervisor = await read('apps/bot-runtime/src/runtime-supervisor.ts')
  // The defect this phase fixed: the session policy used to replace the turn's own ceiling.
  assert.match(supervisor, /effectivePolicy/)
  assert.match(supervisor, /narrowNetworkPolicy/)
  assert.match(supervisor, /narrowPermissionMode/)
  assert.doesNotMatch(supervisor, /permissionMode: this\.policy\.permissionMode\s*\}/)
  const policy = await read('packages/host-protocol/src/bot-policy.ts')
  assert.match(policy, /export function narrowPermissionMode/)
  assert.match(policy, /export function narrowNetworkPolicy/)
})

test('one owner per turn, and one pool of background slots', async () => {
  const scoped = await read('packages/host-core/src/bots/scoped-execution.ts')
  assert.match(scoped, /OwnershipConflict/)
  assert.match(scoped, /claims\.length > 1/)
  const admission = await read('packages/host-core/src/teams/background-admission.ts')
  assert.match(admission, /teamTasks \+ value\.routineOccurrences/)
  const service = await read('packages/host-core/src/bots/service.ts')
  assert.match(service, /CompositeContinuationScope/)
  assert.match(service, /composeDispatchGuards/)
  assert.match(service, /composeBudgetCeilings/)
})

test('audio never becomes a path, a URL or a log line', async () => {
  const voice = await read('packages/host-protocol/src/voice-rpc.ts')
  assert.doesNotMatch(voice, /path:|url:|mimeType/)
  const storage = await read('packages/host-core/src/voice/uploads.ts')
  // Every filename is generated by the Host and checked against that shape.
  assert.match(storage, /GENERATED_ID/)
  const service = await read('packages/host-core/src/voice/service.ts')
  assert.doesNotMatch(service, /console\.(log|info|warn|error)/)
  // Only the confirmed text reaches the engine; the recording is not an attachment.
  assert.match(service, /attachments: \[\]/)
  const worker = await read('apps/host/src/asr-worker.ts')
  assert.doesNotMatch(worker, /console\.(log|info|warn|error)/)
})

test('the application asks for the microphone on a gesture, and for nothing else', async () => {
  const permissions = await read('apps/bot-desktop/src/main/microphone-permissions.ts')
  // Both handlers, or the synchronous check answers its default.
  assert.match(permissions, /setPermissionRequestHandler/)
  assert.match(permissions, /setPermissionCheckHandler/)
  assert.match(permissions, /armed/)
  const index = await read('apps/bot-desktop/src/main/index.ts')
  assert.match(index, /installMicrophonePermissions/)
  // The old blanket refusal is gone, but nothing grants "media" wholesale either.
  assert.doesNotMatch(index, /setPermissionRequestHandler\(\(_contents, _permission, callback\) => callback\(false\)\)/)
  const builder = await read('apps/bot-desktop/electron-builder.yml')
  assert.match(builder, /NSMicrophoneUsageDescription/)
  assert.match(builder, /entitlements: build\/entitlements\.mac\.plist/)
  const entitlements = await read('apps/bot-desktop/build/entitlements.mac.plist')
  assert.match(entitlements, /com\.apple\.security\.device\.audio-input/)
  // The camera is deliberately absent, and nothing disables the sandbox or Gatekeeper.
  assert.doesNotMatch(entitlements, /device\.camera/)
  assert.doesNotMatch(entitlements, /app-sandbox/)
})

test('the packaged application carries no fixture of any kind', async () => {
  const fixtureRoutines = await read('apps/bot-desktop/src/main/fixture-routines.ts')
  const fixtureVoice = await read('apps/bot-desktop/src/main/fixture-voice.ts')
  for (const source of [fixtureRoutines, fixtureVoice]) assert.match(source, /Development-only/)
  const index = await read('apps/bot-desktop/src/main/index.ts')
  // Fixtures exist only when the app is not packaged.
  assert.match(index, /!app\.isPackaged && process\.env\.MAESTRLY_BOT_FIXTURE === '1'/)
})

test('the laboratory asks before it does anything, and prints nothing private', async () => {
  const lab = await read('scripts/bot-routines-lab.mjs')
  assert.match(lab, /ROUTINE_LAB_NOT_AUTHORIZED/)
  assert.match(lab, /VOICE_LAB_NOT_AUTHORIZED/)
  assert.match(lab, /ROUTINE_TARGET_REQUIRED/)
  // It never records anybody: the sample is a file the operator consented to.
  assert.match(lab, /VOICE_SAMPLE_REQUIRED/)
  assert.doesNotMatch(lab, /getUserMedia|MediaRecorder/)
  // Transcripts and summaries are reported by length, never by content.
  assert.match(lab, /transcriptLength/)
  assert.match(lab, /summaryLength/)
})

test('the reported service version matches the package that is built and shipped', async () => {
  // These two drifted apart before: `host.inspect` said one thing and the package manifest another,
  // and the rollout kit compares exactly these to refuse a downgrade. A mismatch would let an
  // operator install something older than what is running.
  const declared = JSON.parse(await read('apps/host/package.json')).version
  const reported = /serviceVersion: '([^']+)'/.exec(await read('packages/host-core/src/service.ts'))?.[1]
  assert.equal(reported, declared)
})

test('the phase is wired into the repository checks', async () => {
  const manifest = JSON.parse(await read('package.json'))
  for (const script of ['check:bot-phase5', 'test:bot-phase5', 'test:e2e:bot-phase5', 'build:host:asr', 'lab:bot:phase5'])
    assert.ok(manifest.scripts[script], `missing script ${script}`)
  // The aggregate check and test include the new phase.
  assert.match(manifest.scripts.check, /check:bot-phase5/)
  assert.match(manifest.scripts.test, /test:bot-phase5/)
  // The laboratory is never part of an automated run.
  assert.doesNotMatch(manifest.scripts.test, /lab:bot:phase5/)
  assert.doesNotMatch(manifest.scripts['test:bot-phase5'], /lab:|ssh/)
})
