#!/usr/bin/env node
// Compiles the browser shell (src/shell) and embeds the result as strings in src/generated/shell-assets.ts, so the
// host serves it from memory and consumers need no extra files at runtime.
import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const out = path.join(root, 'build', 'shell')
const target = path.join(root, 'src', 'generated', 'shell-assets.ts')
const JS = 'text/javascript; charset=utf-8'
const CSS = 'text/css; charset=utf-8'

function fail(message) {
  process.stderr.write(`[embed-shell] ${message}\n`)
  process.exit(1)
}

rmSync(out, { recursive: true, force: true })
const tsc = createRequire(import.meta.url).resolve('typescript/bin/tsc')
const compiled = spawnSync(process.execPath, [tsc, '-p', path.join(root, 'tsconfig.shell.json')], { stdio: 'inherit' })
if (compiled.status !== 0) fail('the shell does not compile')

const files = {}
for (const name of readdirSync(out)
  .filter((entry) => entry.endsWith('.js') && entry !== 'bridge.js')
  .sort()) {
  const body = readFileSync(path.join(out, name), 'utf8')
  for (const match of body.matchAll(/(?:import|export)[^'"]*from\s*['"]([^'"]+)['"]|import\(\s*['"]([^'"]+)['"]/g)) {
    const specifier = match[1] ?? match[2]
    if (!/^\.\/[a-z0-9-]+\.js$/.test(specifier)) fail(`${name} imports ${specifier}; the shell may only import siblings`)
  }
  files[name] = { contentType: JS, body }
}
files['viewer.css'] = { contentType: CSS, body: readFileSync(path.join(root, 'src', 'shell', 'viewer.css'), 'utf8') }

const bridge = readFileSync(path.join(out, 'bridge.js'), 'utf8')
if (/^\s*(?:import|export)\b/m.test(bridge)) fail('bridge.js must be a classic script without imports or exports')

const hash = createHash('sha256')
for (const [name, file] of Object.entries(files)) hash.update(`${name}\0${file.body}\0`)
hash.update(`bridge.js\0${bridge}`)
const version = hash.digest('hex').slice(0, 16)

mkdirSync(path.dirname(target), { recursive: true })
writeFileSync(
  target,
  [
    '// Generated by scripts/embed-shell.mjs. Do not edit.',
    `export const SHELL_VERSION = ${JSON.stringify(version)}`,
    `export const SHELL_FILES: Readonly<Record<string, { contentType: string; body: string }>> = ${JSON.stringify(files, null, 2)}`,
    `export const BRIDGE_SCRIPT = ${JSON.stringify(bridge)}`,
    '',
  ].join('\n')
)
