import { expect,test } from '@playwright/test'
import { translate,type Locale } from '../src/i18n/index.js'

test('real API: columns, Markdown, history, subtasks, lifecycle and repositories',async({page},info)=>{
  test.skip(!process.env.MAESTRLY_LIVE_E2E,'Run with scripts/test-kanban-e2e.mjs for an isolated database.')
  test.setTimeout(120_000)
  const L=(key:string)=>translate(key,info.project.name as Locale)
  await page.setViewportSize({width:1440,height:900})
  await page.goto('/')
  await page.getByRole('textbox',{name:L('Email'),exact:true}).fill(process.env.MAESTRLY_E2E_EMAIL!)
  await page.getByLabel(L('Password'),{exact:true}).fill(process.env.MAESTRLY_E2E_PASSWORD!)
  await page.getByRole('button',{name:L('Sign in'),exact:true}).click()
  await expect(page.getByRole('navigation',{name:L('Workspace')})).toBeVisible()
  const headers={'x-maestrly-protocol-version':'1.0','idempotency-key':crypto.randomUUID()}
  const orgs=await (await page.request.get('/api/v1/organizations',{headers})).json()
  const org=orgs[0].id
  const name='Live '+info.project.name+' '+Date.now()
  const created=await (await page.request.post('/api/v1/organizations/'+org+'/projects',{headers,data:{name}})).json()
  expect(created.project?.id).toBeTruthy()
  await page.reload()
  await page.getByRole('combobox',{name:L('Project'),exact:true}).click()
  await page.getByRole('option',{name,exact:true}).click()
  await expect(page.locator('h1')).toHaveText(name)
  await page.getByRole('button',{name:L('Add column'),exact:true}).click()
  let dialog=page.getByRole('dialog')
  await dialog.getByLabel(L('Column name'),{exact:true}).fill('Validation')
  await dialog.getByRole('button',{name:L('Save changes'),exact:true}).click()
  await expect(page.getByRole('heading',{name:'Validation',exact:true})).toBeVisible()
  await page.getByRole('button',{name:L('Rename column')+' Validation',exact:true}).click()
  await dialog.getByLabel(L('Column name'),{exact:true}).fill('Quality')
  await dialog.getByRole('button',{name:L('Save changes'),exact:true}).click()
  await page.getByRole('button',{name:L('Move column left')+' Quality',exact:true}).click()
  await expect(page.locator('.board-column').nth(2).getByRole('heading')).toHaveText('Quality')
  const column=page.locator('.board-column').filter({has:page.getByRole('heading',{name:'Quality',exact:true})})
  await column.getByRole('button',{name:L('Add card'),exact:true}).click()
  await dialog.getByRole('textbox',{name:L('Title'),exact:true}).fill('Workflow card')
  await dialog.getByRole('textbox',{name:L('Description'),exact:true}).fill('# Original\n\n- [ ] Check delivery')
  await dialog.getByRole('button',{name:L('Create card'),exact:true}).click()
  await expect(page.getByRole('button',{name:'Workflow card',exact:true})).toBeVisible()
  await page.getByRole('button',{name:L('Delete column')+' Quality',exact:true}).click()
  await dialog.getByRole('combobox',{name:L('Move cards to')}).click()
  await page.getByRole('option',{name:'Backlog',exact:true}).click()
  await dialog.getByRole('button',{name:L('Delete'),exact:true}).click()
  await expect(page.getByRole('heading',{name:'Quality',exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'Workflow card',exact:true}).click()
  dialog=page.getByRole('dialog')
  await expect(dialog.getByRole('tab',{name:L('General'),exact:true})).toBeVisible()
  await expect(dialog.locator('[contenteditable=true]').first()).toBeVisible()
  await dialog.getByRole('button',{name:L('Write'),exact:true}).first().click()
  await dialog.getByRole('textbox',{name:L('Description'),exact:true}).fill('# Revised\n\n**Rich Markdown**\n\n```ts\nconst safe = true\n```')
  await expect(dialog.getByRole('status')).toHaveText(L('All changes saved'))
  await dialog.getByRole('button',{name:L('Preview'),exact:true}).first().click()
  await expect(dialog.locator('.markdown-content strong').filter({hasText:'Rich Markdown'})).toBeVisible()
  await dialog.getByRole('textbox',{name:L('Labels'),exact:true}).fill('web, release')
  await dialog.getByRole('textbox',{name:L('Acceptance criteria'),exact:true}).fill('Verified output')
  await dialog.getByRole('combobox',{name:L('Priority'),exact:true}).click()
  await page.getByRole('option',{name:L('urgent'),exact:true}).click()
  await dialog.getByRole('checkbox',{name:'Maestrly owner',exact:true}).check()
  await dialog.getByRole('button',{name:L('Save changes'),exact:true}).click()
  await expect(dialog.getByText(L('Changes saved.'),{exact:true})).toBeVisible()
  await dialog.getByRole('tab',{name:new RegExp('^'+L('Comments'))}).click()
  await dialog.getByRole('textbox',{name:L('Comment'),exact:true}).fill('**Review note**\n\n<script>window.injected=true</script>')
  await dialog.getByRole('button',{name:L('Preview'),exact:true}).click()
  await expect(dialog.locator('.markdown-content strong').filter({hasText:'Review note'})).toBeVisible()
  await dialog.getByRole('button',{name:L('Comment'),exact:true}).click()
  await expect(dialog.locator('.comment-entry strong').filter({hasText:'Review note'})).toBeVisible()
  expect(await page.evaluate(()=>Reflect.get(window,'injected'))).toBeUndefined()
  await dialog.getByRole('button',{name:L('Edit'),exact:true}).click()
  await dialog.getByRole('button',{name:L('Write'),exact:true}).click()
  await dialog.getByRole('textbox',{name:L('Comment'),exact:true}).fill('**Edited note**')
  await dialog.getByRole('button',{name:L('Save comment'),exact:true}).click()
  await expect(dialog.locator('.comment-entry')).toContainText('Edited note')
  await dialog.getByRole('tab',{name:L('History'),exact:true}).click()
  await expect(dialog.locator('.history-list button')).toHaveCount(2)
  await dialog.locator('.history-list button').last().click()
  await dialog.getByRole('button',{name:L('Restore version'),exact:true}).click()
  await expect(dialog.locator('.history-list button')).toHaveCount(3)
  await dialog.getByRole('tab',{name:L('General'),exact:true}).click()
  await expect(dialog.locator('.markdown-content h1')).toHaveText('Original')
  await dialog.getByRole('button',{name:L('Add subtask'),exact:true}).click()
  const subdialog=page.getByRole('dialog',{name:L('Add subtask'),exact:true})
  await subdialog.getByRole('textbox',{name:L('Title'),exact:true}).fill('Child work')
  await subdialog.getByRole('button',{name:L('Create card'),exact:true}).click()
  await expect(dialog.getByRole('button',{name:/Child work/})).toBeVisible()
  await dialog.getByRole('tab',{name:L('Events'),exact:true}).click()
  await expect(dialog.locator('.timeline-entry')).not.toHaveCount(0)
  await dialog.getByRole('tab',{name:L('General'),exact:true}).click()
  for(const width of [1440,390]) {
    await page.setViewportSize({width,height:900})
    for(const theme of ['light','dark']) {
      await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme)
      await page.screenshot({path:info.outputPath('card-'+width+'-'+theme+'.png'),animations:'disabled'})
      expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    }
  }
  await dialog.getByRole('button',{name:L('Archive'),exact:true}).click()
  await page.getByRole('dialog',{name:L('Archive card'),exact:true}).getByRole('button',{name:L('Confirm'),exact:true}).click()
  await expect(page.getByRole('button',{name:'Workflow card',exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:L('Archived cards'),exact:true}).click()
  await page.getByRole('button',{name:'Workflow card',exact:true}).click()
  await dialog.getByRole('button',{name:L('Restore'),exact:true}).click()
  await page.getByRole('dialog',{name:L('Restore card'),exact:true}).getByRole('button',{name:L('Confirm'),exact:true}).click()
  await page.getByRole('button',{name:L('Archived cards'),exact:true}).click()
  await page.getByRole('button',{name:'Workflow card',exact:true}).click()
  await dialog.getByRole('button',{name:L('Delete card'),exact:true}).click()
  await page.getByRole('dialog',{name:L('Delete card'),exact:true}).getByRole('button',{name:L('Confirm'),exact:true}).click()
  await expect(page.getByRole('button',{name:'Workflow card',exact:true})).toHaveCount(0)
  await page.getByRole('navigation',{name:L('Workspace')}).getByRole('button',{name:L('Git repositories'),exact:true}).click()
  await page.getByRole('button',{name:L('Add repository'),exact:true}).click()
  await dialog.getByRole('textbox',{name:L('Repository name'),exact:true}).fill('Source')
  await dialog.getByRole('textbox',{name:L('Base branch'),exact:true}).fill('release')
  await dialog.getByRole('button',{name:L('Save changes'),exact:true}).click()
  await expect(page.locator('.data-list')).toContainText('Source')
  await page.getByRole('navigation',{name:L('Workspace')}).getByRole('button',{name:L('Runners'),exact:true}).click()
  await expect(page.getByText(L('No compatible runner is reporting this repository and branch.'))).toBeVisible()
  await page.getByRole('button',{name:L('Enroll runner'),exact:true}).click()
  await expect(page.locator('.enrollment-box pre')).toContainText('maestrly-runner enroll')
  await page.getByRole('navigation',{name:L('Workspace')}).getByRole('button',{name:L('Board'),exact:true}).click()
  await page.getByRole('button',{name:L('Create board'),exact:true}).click()
  await dialog.getByRole('textbox',{name:L('Board name'),exact:true}).fill('Empty pipeline')
  await dialog.getByRole('combobox',{name:L('Template'),exact:true}).click()
  await page.getByRole('option',{name:L('blank'),exact:true}).click()
  await dialog.getByRole('button',{name:L('Save changes'),exact:true}).click()
  await expect(page.getByText(L('No columns yet.'),{exact:true})).toBeVisible()
  await page.getByRole('button',{name:L('Archive board'),exact:true}).click()
  await dialog.getByRole('button',{name:L('Archive'),exact:true}).click()
  await page.getByRole('button',{name:L('Archived boards'),exact:true}).click()
  await page.locator('.archived-boards').getByRole('button',{name:L('Restore'),exact:true}).click()
  await dialog.getByRole('button',{name:L('Restore'),exact:true}).click()
  await expect(page.locator('.board-tabs').getByRole('button',{name:'Empty pipeline',exact:true})).toHaveAttribute('aria-pressed','true')
})
