import { toolOutputText, type ChatMessage, type MessagePart } from '../../shared/chat'
import type { NormalizedAiUsage } from './runner'
import { activeChatContext, nativeSeedContextText, renderNativeSeedTranscript } from './message'

/** A deliberately conservative text/code heuristic. UTF-8 bytes avoid undercounting non-ASCII conversations. */
export function estimateTextTokens(text: string): number {
  if (!text) return 0
  return Math.ceil(Buffer.byteLength(text, 'utf8') / 3)
}

function toolOutput(part: Extract<MessagePart, { type: 'tool' }>): string {
  switch (part.state.status) {
    case 'completed':
      return toolOutputText(part.state.output)
    case 'running':
      return toolOutputText(part.state.output)
    case 'error':
      return part.state.error
    case 'denied':
      return part.state.reason ?? ''
    default:
      return '(the tool did not finish)'
  }
}

/** Estimates the portable payload Maestrly reconstructs, excluding display-only reasoning. */
export function estimatePortablePartsTokens(parts: readonly MessagePart[]): number {
  let tokens = 0
  for (const part of parts) {
    if (part.type === 'text') {
      if (part.checkpoint !== 'openai-native') tokens += estimateTextTokens(part.text)
    } else if (part.type === 'file') {
      // Image payloads are provider-tokenized; counting base64 would overestimate by orders of magnitude.
      tokens += part.kind === 'image' ? 8_192 : estimateTextTokens(part.data ?? '')
      tokens += estimateTextTokens(part.name) + 12
    } else if (part.type === 'context' || part.type === 'compaction') {
      tokens += estimateTextTokens(part.text)
    } else if (part.type === 'generated-image') {
      // Reconstruct only the textual reference — generated bytes never reenter context.
      tokens += estimateTextTokens(part.name) + estimateTextTokens(part.revisedPrompt ?? '') + 12
    } else if (part.type === 'skill-invocation') {
      // The model receives the expanded BODY (`/name` chip is display-only).
      tokens += estimateTextTokens(part.body) + estimateTextTokens(part.args ?? '')
    } else if (part.type === 'tool') {
      let input = ''
      try {
        input = JSON.stringify(part.input ?? {})
      } catch {
        input = String(part.input ?? '')
      }
      tokens +=
        estimateTextTokens(part.toolName) + estimateTextTokens(input) + estimateTextTokens(toolOutput(part)) + 24
    }
  }
  return tokens
}

/** Portable context after the latest textual compaction marker. Native opaque checkpoints are ignored. */
export function estimatePortableContextTokens(messages: readonly ChatMessage[]): number {
  const active = activeChatContext([...messages])
  let tokens = active.summary ? estimateTextTokens(active.summary) + 24 : 0
  for (const message of active.messages) tokens += estimatePortablePartsTokens(message.parts) + 16
  return tokens
}

/** Estimates the bounded textual payload used to seed a fresh native runtime session/thread. */
export function estimateNativeSeedContextTokens(messages: readonly ChatMessage[]): number {
  const transcript = renderNativeSeedTranscript(messages)
  return estimateTextTokens(nativeSeedContextText(transcript))
}

/** Space not represented by transcript rows: system prompt, tools, the pending turn and model output. */
export function portableContextReserveTokens(contextWindow: number): number {
  return Math.max(16_384, Math.min(64_000, Math.ceil(contextWindow * 0.1)))
}

/**
 * Headroom for the next model step when occupancy is already measured by the provider.
 * Measured usage already includes system/tools from the previous request — only pending +
 * next-step output still need slack. Must stay well below the full portable reserve so a
 * custom limit (e.g. 300k on a 1M model) is not double-counted into artificial overflow.
 */
export function portableContextOutputReserveTokens(contextWindow: number): number {
  return Math.max(4_096, Math.min(32_000, Math.ceil(contextWindow * 0.05)))
}

export type ContextProjectionSource = 'runtime-usage' | 'portable-transcript'

export interface PortableContextLoad {
  requiredTokens: number
  reserveTokens: number
  ratio: number
  shouldCompact: boolean
  overflow: boolean
}

export function portableContextLoad(
  contextWindow: number,
  historyTokens: number,
  pendingTokens: number,
  compactRatio = 0.9
): PortableContextLoad {
  const reserveTokens = portableContextReserveTokens(contextWindow)
  const requiredTokens = Math.max(0, historyTokens) + Math.max(0, pendingTokens) + reserveTokens
  const ratio = contextWindow > 0 ? requiredTokens / contextWindow : Number.POSITIVE_INFINITY
  return {
    requiredTokens,
    reserveTokens,
    ratio,
    shouldCompact: ratio >= compactRatio,
    overflow: requiredTokens >= contextWindow,
  }
}

/**
 * Preflight admission load: source-aware variant of {@link portableContextLoad}.
 * - `portable-transcript`: full conservative reserve (system/tools/output not in the estimate).
 * - `runtime-usage`: measured occupancy already includes system/tools — only pending + output slack.
 */
export function preflightContextLoad(
  contextWindow: number,
  historyTokens: number,
  pendingTokens: number,
  source: ContextProjectionSource,
  compactRatio = 0.9
): PortableContextLoad {
  if (source === 'portable-transcript') {
    return portableContextLoad(contextWindow, historyTokens, pendingTokens, compactRatio)
  }
  const reserveTokens = portableContextOutputReserveTokens(contextWindow)
  const requiredTokens = Math.max(0, historyTokens) + Math.max(0, pendingTokens) + reserveTokens
  const ratio = contextWindow > 0 ? requiredTokens / contextWindow : Number.POSITIVE_INFINITY
  return {
    requiredTokens,
    reserveTokens,
    ratio,
    shouldCompact: ratio >= compactRatio,
    overflow: requiredTokens >= contextWindow,
  }
}

/** Splits every character exactly once, preferring paragraph/newline boundaries where possible. */
export function splitPortableTranscript(text: string, maxChars: number): string[] {
  const limit = Math.max(1_000, Math.floor(maxChars))
  const chunks: string[] = []
  let offset = 0
  while (offset < text.length) {
    let end = Math.min(text.length, offset + limit)
    if (end < text.length) {
      const floor = offset + Math.floor(limit * 0.6)
      const paragraph = text.lastIndexOf('\n\n', end)
      const newline = text.lastIndexOf('\n', end)
      const boundary = paragraph >= floor ? paragraph + 2 : newline >= floor ? newline + 1 : end
      end = Math.max(offset + 1, boundary)
    }
    chunks.push(text.slice(offset, end))
    offset = end
  }
  return chunks
}

export interface PortableSummaryCallResult {
  text: string
  usage?: NormalizedAiUsage
  runtimeEstimatedCostUsd?: number
}

export interface PortableSummaryResult {
  summary: string
  usage?: NormalizedAiUsage
  runtimeEstimatedCostUsd?: number
  calls: number
}

function addUsage(total: NormalizedAiUsage, next?: NormalizedAiUsage): void {
  if (!next) return
  total.input += next.input
  total.output += next.output
  total.cacheRead += next.cacheRead
  total.cacheCreate += next.cacheCreate
  total.totalInput += next.totalInput
}

/** Map-reduce summarization: every source chunk is summarized, then summaries are recursively consolidated. */
export async function summarizePortableTranscript(
  transcript: string,
  maxChunkChars: number,
  summarize: (prompt: string, phase: 'chunk' | 'consolidate') => Promise<PortableSummaryCallResult>
): Promise<PortableSummaryResult> {
  const usage: NormalizedAiUsage = { input: 0, output: 0, cacheRead: 0, cacheCreate: 0, totalInput: 0 }
  let runtimeEstimatedCostUsd = 0
  let runtimeCostComplete = true
  let calls = 0
  let chunks = splitPortableTranscript(transcript, maxChunkChars)
  if (chunks.length === 0) throw new Error('There is no portable transcript to compact')

  const runLevel = async (source: string[], phase: 'chunk' | 'consolidate'): Promise<string[]> => {
    const output: string[] = []
    for (let index = 0; index < source.length; index += 1) {
      const label =
        phase === 'chunk' ? `Source chunk ${index + 1}/${source.length}` : `Summary group ${index + 1}/${source.length}`
      const result = await summarize(`${label}:\n\n${source[index]}`, phase)
      const text = result.text.trim()
      if (!text) throw new Error('The context compactor returned an empty summary')
      calls += 1
      addUsage(usage, result.usage)
      if (typeof result.runtimeEstimatedCostUsd === 'number' && Number.isFinite(result.runtimeEstimatedCostUsd)) {
        runtimeEstimatedCostUsd += Math.max(0, result.runtimeEstimatedCostUsd)
      } else {
        runtimeCostComplete = false
      }
      output.push(text)
    }
    return output
  }

  chunks = await runLevel(chunks, 'chunk')
  for (let level = 0; chunks.length > 1; level += 1) {
    if (level >= 12) throw new Error('The context compactor did not converge')
    const grouped = splitPortableTranscript(
      chunks.map((chunk, index) => `Summary ${index + 1}:\n${chunk}`).join('\n\n'),
      maxChunkChars
    )
    chunks = await runLevel(grouped, 'consolidate')
  }
  return {
    summary: chunks[0],
    ...(usage.totalInput || usage.output ? { usage } : {}),
    ...(calls > 0 && runtimeCostComplete ? { runtimeEstimatedCostUsd } : {}),
    calls,
  }
}
