import { expect, test } from '@playwright/test'
import { launchBot, readyBot, send, computers } from './bot-helpers'

test('a second bot gets its own workspace in the same VM while the first keeps working', async () => {
  const { app, page } = await launchBot()
  try {
    await readyBot(page, 'Pesquisa A')
    await send(page, '#slow A')
    await expect(page.getByRole('button', { name: 'Parar tarefa', exact: true })).toBeVisible()
    const before = await page.evaluate(() => window.bot.call({ method: 'vm.list', params: {} }))
    await page.getByRole('button', { name: 'Novo bot', exact: true }).click()
    await page.getByLabel('Nome', { exact: true }).fill('Pesquisa B')
    await page.getByRole('button', { name: 'Continuar', exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Ambiente', exact: true })).toContainText('Build worker')
    await expect(page.getByLabel('Autorizo a preparação e o backup')).toHaveCount(0)
    await page.screenshot({ animations: 'disabled', path: 'test-results/shared-vm-setup.png' })
    await page.getByRole('button', { name: 'Continuar', exact: true }).click()
    await expect(page.getByText('fixture@example.test', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Criar bot', exact: true }).click()
    await expect(page.locator('.chat-header h1')).toHaveText('Pesquisa B')
    expect(await page.evaluate(() => window.bot.call({ method: 'vm.list', params: {} }))).toEqual(before)
    const identities = await page.evaluate(async () => {
      const bots = await window.bot.bot({ method: 'bot.list', params: {} })
      return Promise.all(bots.map(async bot => ({ bot, session: await window.bot.bot({ method: 'bot.session.inspect', params: { botId: bot.id } }) })))
    })
    expect(identities[0].bot.accountId).toBe(identities[1].bot.accountId)
    expect(identities[0].bot.vmId).toBe(identities[1].bot.vmId)
    expect(identities[0].session?.id).not.toBe(identities[1].session?.id)
    expect(identities[0].bot.activeTurnId).toBeTruthy()
    await send(page, '#slow B')
    await page.getByRole('button', { name: 'Parar tarefa', exact: true }).click()
    await page.getByRole('button', { name: 'Pesquisa A', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Parar tarefa', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Detalhes', exact: true }).click()
    await expect(page.getByText('Área de trabalho exclusiva', { exact: true })).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: 'test-results/shared-vm-details.png' })
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Parar tarefa', exact: true }).click()
    await expect(page.locator('.chat-header')).toContainText('Tarefa interrompida')
    await computers(page)
    await page.locator('#alias').fill('local')
    await page.getByRole('button', { name: 'Conectar', exact: true }).click()
    await expect(page.locator('.capacity')).toBeVisible()
    await page.getByRole('button', { name: /Build worker/ }).click()
    await page.locator('.detail').getByRole('button', { name: 'Reiniciar', exact: true }).click()
    await expect(page.getByRole('dialog')).toContainText('Pesquisa A')
    await expect(page.getByRole('dialog')).toContainText('Pesquisa B')
    await page.screenshot({ animations: 'disabled', path: 'test-results/shared-vm-impact.png' })
    await page.getByRole('dialog').getByRole('button', { name: 'Cancelar', exact: true }).click()
  } finally { await app.close() }
})

test('an old environment offers preparation only in Environments', async () => {
  const { app, page } = await launchBot({ MAESTRLY_BOT_FIXTURE_READY_ENVIRONMENT: '0' })
  try {
    await page.getByRole('button', { name: 'Criar meu primeiro bot' }).click()
    await page.getByRole('button', { name: 'Continuar', exact: true }).click()
    await expect(page.getByText('Prepare ou ligue um ambiente para criar seu bot.')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Continuar', exact: true })).toBeDisabled()
    await expect(page.getByLabel('Autorizo a preparação e o backup')).toHaveCount(0)
    await page.getByRole('button', { name: 'Gerenciar ambientes', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Ambientes', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Criar ambiente', exact: true }).click()
    await page.getByRole('dialog').getByLabel('Nome', { exact: true }).fill('Ambiente preparado')
    await page.getByRole('dialog').getByRole('button', { name: 'Criar ambiente', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Ambiente preparado', exact: true })).toBeVisible()
    await page.screenshot({ path: 'test-results/environments.png' })
    expect(await page.evaluate(async () => (await window.bot.bot({ method: 'bot.list', params: {} })).length)).toBe(0)
    await page.getByRole('button', { name: 'Voltar para criar o bot', exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Ambiente', exact: true })).toContainText('Ambiente preparado')
    await expect(page.getByRole('button', { name: 'Continuar', exact: true })).toBeEnabled()
  } finally { await app.close() }
})

test('shared account disconnect displays affected bots and model controls work in simple mode', async () => {
  const { app, page } = await launchBot()
  try {
    await readyBot(page, 'Bot geral')
    await page.getByRole('button', { name: 'Detalhes', exact: true }).click()
    await page.getByRole('region', { name: 'Detalhes', exact: true }).getByRole('button', { name: 'Modelo', exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Modelo', exact: true })).toBeVisible()
    await expect(page.getByRole('combobox', { name: 'Esforço', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await send(page, '#slow')
    await expect(page.getByRole('button', { name: 'Parar tarefa', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Contas', exact: true }).click()
    await page.getByRole('button', { name: 'Sair da conta', exact: true }).click()
    await expect(page.getByRole('dialog')).toContainText('Bot geral')
    await expect(page.getByRole('dialog').getByRole('button', { name: 'Sair da conta', exact: true })).toBeDisabled()
    await page.screenshot({ path: 'test-results/shared-account-impact.png' })
    await page.getByRole('dialog').getByRole('button', { name: 'Cancelar', exact: true }).click()
    await page.getByRole('button', { name: 'Bot geral', exact: true }).click()
    await page.getByRole('button', { name: 'Parar tarefa', exact: true }).click()
    await expect(page.locator('.chat-header')).toContainText('Tarefa interrompida')
    await page.getByRole('button', { name: 'Contas', exact: true }).click()
    await page.getByRole('button', { name: 'Sair da conta', exact: true }).click()
    await expect(page.getByRole('dialog').getByRole('button', { name: 'Sair da conta', exact: true })).toBeEnabled()
    await page.getByRole('dialog').getByRole('button', { name: 'Sair da conta', exact: true }).click()
    await expect(page.getByText('Conta desconectada', { exact: true })).toBeVisible()
  } finally { await app.close() }
})
