/**
 * In-memory controller for a ChatGPT Web project-environment bootstrap.
 *
 * The caller resolves and validates an enabled project skill before calling `start`. This module deliberately
 * has no command/prompt entry point: the only model instructions it accepts are the validated skill name/body,
 * which are embedded in a controller-owned prompt with fixed workspace-safety constraints.
 *
 * One controller belongs to one companion session/conversation. It admits at most one internal turn at a time
 * and keeps the slot occupied through cancellation until the InternalTurnHandle reports a terminal outcome.
 */
import { createHash, randomUUID } from 'node:crypto'
import type { FrozenChatSelection, InternalTurnHandle, InternalTurnOutcome } from '../../../shared/chat'

export const PROJECT_ENVIRONMENT_MAX_WAIT_SECONDS = 60
export const PROJECT_ENVIRONMENT_DEFAULT_WAIT_SECONDS = 30
export const PROJECT_ENVIRONMENT_MAX_SKILL_NAME_CHARS = 200
export const PROJECT_ENVIRONMENT_MAX_SKILL_BODY_CHARS = 64_000

const IDEMPOTENCY_CACHE_LIMIT = 64
const FINISHED_JOB_LIMIT = 32

export type ProjectEnvironmentJobStatus = 'starting' | 'running' | 'cancelling' | 'completed' | 'failed' | 'cancelled'

export interface StartProjectEnvironmentJobInput {
  /** Name of an already-resolved, enabled project skill. */
  skillName: string
  /** Body of that same validated skill. Raw user prompts and shell commands are not accepted. */
  skillBody: string
  idempotencyKey: string
}

export interface ProjectEnvironmentJobStartResult {
  jobId: string
  status: 'running'
  startedAt: number
  skillName: string
  executor: { providerId: string; modelId: string; reasoning?: string }
}

export interface ProjectEnvironmentJobInfo {
  jobId: string
  status: ProjectEnvironmentJobStatus
  startedAt: number
  finishedAt?: number
  skillName: string
  executionId?: string
  assistantMessageId?: string
  /** Present only after InternalTurnHandle.done produces a terminal outcome. */
  outcome?: InternalTurnOutcome
  error?: string
}

export type ProjectEnvironmentResult<T> = T | { error: string }

export interface ProjectEnvironmentJobDeps {
  /** Scopes all jobs and InternalTurnHandles owned by this controller. */
  conversationId: string
  /** Optional opaque companion-session identifier for diagnostics/integration ownership. */
  sessionId?: string
  now?: () => number
  sessionActive: () => boolean
  /** Conversation can admit an automated turn (no active operation/plan conflict). */
  validateStart: () => Promise<{ ok: true } | { ok: false; error: string }>
  /** Resolve and freeze the local executor selected for this conversation. */
  resolveSelection: () => Promise<{ ok: true; selection: FrozenChatSelection } | { ok: false; error: string }>
  /** Start exactly one local-agent turn. `prompt` is always generated by this controller. */
  startTurn: (input: {
    prompt: string
    selection: FrozenChatSelection
    jobId: string
    skillName: string
    signal: AbortSignal
  }) => Promise<{ ok: true; handle: InternalTurnHandle } | { ok: false; error: string }>
  cancelTurn: (executionId: string) => void
  forceAgentMode: () => void
  onChange?: () => void
}

interface ProjectEnvironmentJob {
  jobId: string
  skillName: string
  startedAt: number
  finishedAt?: number
  status: ProjectEnvironmentJobStatus
  controller: AbortController
  selection?: FrozenChatSelection
  handle?: InternalTurnHandle
  executionId?: string
  assistantMessageId?: string
  outcome?: InternalTurnOutcome
  error?: string
  cancelDispatched: boolean
  turnCancelDispatched: boolean
  completion: Promise<void>
  settleCompletion: () => void
}

function boundedText(value: unknown, maxChars: number): string | null {
  if (typeof value !== 'string') return null
  const text = value.trim()
  return text && text.length <= maxChars ? text : null
}

function errorText(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}

function fingerprint(input: StartProjectEnvironmentJobInput): string {
  return createHash('sha256').update(input.skillName).update('\0').update(input.skillBody).digest('hex')
}

/**
 * Builds the only prompt this controller can send. The skill is resolved by trusted local code before this
 * boundary; ChatGPT Web cannot provide a shell command or substitute a free-form executor prompt.
 */
export function buildProjectEnvironmentPrompt(skillName: string, skillBody: string): string {
  return [
    'Bootstrap the project environment for this conversation by following the supplied enabled project skill.',
    '',
    `Skill: ${skillName}`,
    '',
    '<project-environment-skill>',
    skillBody,
    '</project-environment-skill>',
    '',
    'Use the terminal and browser tools available in this conversation as needed to follow the skill.',
    'Do not edit, create, delete, or otherwise modify repository files. This job is environment bootstrap only.',
    'Leave services intentionally started by the skill running when the job finishes so this conversation and the ChatGPT Web companion can use them.',
    'Report briefly what is ready, including useful local URLs or ports, and any bootstrap failure.',
  ].join('\n')
}

export function createProjectEnvironmentJobController(deps: ProjectEnvironmentJobDeps) {
  const now = deps.now ?? (() => Date.now())
  const jobs = new Map<string, ProjectEnvironmentJob>()
  const idempotency = new Map<
    string,
    { fingerprint: string; result: Promise<ProjectEnvironmentResult<ProjectEnvironmentJobStartResult>> }
  >()
  let activeJob: ProjectEnvironmentJob | null = null

  const notify = (): void => {
    try {
      deps.onChange?.()
    } catch {
      // Observers cannot affect lifecycle guarantees.
    }
  }

  const publicInfo = (job: ProjectEnvironmentJob): ProjectEnvironmentJobInfo => ({
    jobId: job.jobId,
    status: job.status,
    startedAt: job.startedAt,
    ...(job.finishedAt === undefined ? {} : { finishedAt: job.finishedAt }),
    skillName: job.skillName,
    ...(job.executionId ? { executionId: job.executionId } : {}),
    ...(job.assistantMessageId ? { assistantMessageId: job.assistantMessageId } : {}),
    ...(job.outcome ? { outcome: job.outcome } : {}),
    ...(job.error ? { error: job.error } : {}),
  })

  const remember = (job: ProjectEnvironmentJob): void => {
    jobs.set(job.jobId, job)
    while (jobs.size > FINISHED_JOB_LIMIT) {
      const oldest = jobs.keys().next().value
      if (typeof oldest !== 'string') break
      jobs.delete(oldest)
    }
  }

  const release = (job: ProjectEnvironmentJob): void => {
    if (activeJob === job) activeJob = null
    remember(job)
    job.settleCompletion()
    notify()
  }

  const finishWithoutHandle = (job: ProjectEnvironmentJob, status: 'failed' | 'cancelled', error?: string): void => {
    if (job.finishedAt !== undefined) return
    job.status = status
    job.finishedAt = now()
    if (error) job.error = error
    release(job)
  }

  const applyOutcome = (job: ProjectEnvironmentJob, outcome: InternalTurnOutcome): void => {
    if (job.finishedAt !== undefined) return
    job.outcome = outcome
    try {
      job.assistantMessageId = outcome.assistantMessageId ?? job.handle?.assistantMessageId() ?? undefined
    } catch {
      job.assistantMessageId = outcome.assistantMessageId ?? undefined
    }
    job.status = outcome.status === 'success' ? 'completed' : outcome.status === 'error' ? 'failed' : 'cancelled'
    if (outcome.status === 'error') job.error = outcome.error
    job.finishedAt = now()
    release(job)
  }

  const cancelAttachedTurn = (job: ProjectEnvironmentJob): void => {
    if (!job.handle || job.turnCancelDispatched) return
    job.turnCancelDispatched = true
    try {
      job.handle.cancel()
    } catch {
      // cancelTurn below is the independent cancellation path.
    }
    if (job.executionId) {
      try {
        deps.cancelTurn(job.executionId)
      } catch {
        // The handle outcome remains the canonical terminal signal.
      }
    }
  }

  const dispatchCancellation = (job: ProjectEnvironmentJob): void => {
    if (job.finishedAt !== undefined) return
    if (!job.cancelDispatched) {
      job.cancelDispatched = true
      job.status = 'cancelling'
      job.controller.abort()
    }
    // A stop may have happened while startTurn was still pending. Dispatch again after the late handle is
    // attached, but at most once for that handle.
    cancelAttachedTurn(job)
    notify()
  }

  const attachHandle = (job: ProjectEnvironmentJob, handle: InternalTurnHandle): string | null => {
    job.handle = handle
    job.executionId = handle.executionId
    if (handle.conversationId !== deps.conversationId) {
      const mismatchError = 'turn-conversation-mismatch'
      job.error = mismatchError
      dispatchCancellation(job)
      // The foreign handle is still an active turn even though this controller cannot accept its outcome.
      // Retain the sole job slot until that handle settles so another bootstrap cannot overlap it.
      void handle.done.then(
        () => finishWithoutHandle(job, 'failed', mismatchError),
        () => finishWithoutHandle(job, 'failed', mismatchError)
      )
      return mismatchError
    }
    job.status = job.controller.signal.aborted ? 'cancelling' : 'running'
    void handle.done.then(
      (outcome) => applyOutcome(job, outcome),
      (error) => finishWithoutHandle(job, 'failed', `turn-outcome-rejected:${errorText(error)}`)
    )
    if (job.controller.signal.aborted) dispatchCancellation(job)
    notify()
    return null
  }

  const validateInput = (
    raw: StartProjectEnvironmentJobInput
  ): { input: StartProjectEnvironmentJobInput } | { error: string } => {
    if (!raw || typeof raw !== 'object') return { error: 'invalid-start-input' }
    const record = raw as unknown as Record<string, unknown>
    if (
      Object.hasOwn(record, 'prompt') ||
      Object.hasOwn(record, 'command') ||
      Object.hasOwn(record, 'rawCommand') ||
      Object.hasOwn(record, 'freeformPrompt')
    ) {
      return { error: 'raw-execution-not-allowed' }
    }
    const unknown = Object.keys(record).find(
      (key) => key !== 'skillName' && key !== 'skillBody' && key !== 'idempotencyKey'
    )
    if (unknown) return { error: 'invalid-start-input' }
    const skillName = boundedText(record.skillName, PROJECT_ENVIRONMENT_MAX_SKILL_NAME_CHARS)
    const skillBody = boundedText(record.skillBody, PROJECT_ENVIRONMENT_MAX_SKILL_BODY_CHARS)
    const idempotencyKey = boundedText(record.idempotencyKey, 256)
    if (!skillName) return { error: 'invalid-skill-name' }
    if (!skillBody) return { error: 'invalid-skill-body' }
    if (!idempotencyKey) return { error: 'invalid-idempotency-key' }
    return { input: { skillName, skillBody, idempotencyKey } }
  }

  async function doStart(
    input: StartProjectEnvironmentJobInput
  ): Promise<ProjectEnvironmentResult<ProjectEnvironmentJobStartResult>> {
    if (!deps.sessionActive()) return { error: 'session-not-active' }
    if (activeJob) return { error: activeJob.status === 'cancelling' ? 'job-stopping' : 'job-active' }

    let settleCompletion!: () => void
    const completion = new Promise<void>((resolve) => {
      settleCompletion = resolve
    })
    const job: ProjectEnvironmentJob = {
      jobId: `pej_${randomUUID()}`,
      skillName: input.skillName,
      startedAt: now(),
      status: 'starting',
      controller: new AbortController(),
      cancelDispatched: false,
      turnCancelDispatched: false,
      completion,
      settleCompletion,
    }
    activeJob = job
    notify()

    let validated: Awaited<ReturnType<ProjectEnvironmentJobDeps['validateStart']>>
    try {
      validated = await deps.validateStart()
    } catch (error) {
      finishWithoutHandle(job, job.controller.signal.aborted ? 'cancelled' : 'failed', errorText(error))
      return { error: job.controller.signal.aborted ? 'job-cancelled' : 'start-validation-failed' }
    }
    if (job.controller.signal.aborted) {
      finishWithoutHandle(job, 'cancelled')
      return { error: 'job-cancelled' }
    }
    if (!validated.ok) {
      finishWithoutHandle(job, 'failed', validated.error)
      return { error: validated.error }
    }
    if (!deps.sessionActive()) {
      finishWithoutHandle(job, 'cancelled')
      return { error: 'session-not-active' }
    }

    let selected: Awaited<ReturnType<ProjectEnvironmentJobDeps['resolveSelection']>>
    try {
      selected = await deps.resolveSelection()
    } catch (error) {
      finishWithoutHandle(job, job.controller.signal.aborted ? 'cancelled' : 'failed', errorText(error))
      return { error: job.controller.signal.aborted ? 'job-cancelled' : 'selection-failed' }
    }
    if (job.controller.signal.aborted) {
      finishWithoutHandle(job, 'cancelled')
      return { error: 'job-cancelled' }
    }
    if (!selected.ok) {
      finishWithoutHandle(job, 'failed', selected.error)
      return { error: selected.error }
    }
    if (!deps.sessionActive()) {
      finishWithoutHandle(job, 'cancelled')
      return { error: 'session-not-active' }
    }
    job.selection = selected.selection

    try {
      deps.forceAgentMode()
    } catch (error) {
      finishWithoutHandle(job, 'failed', errorText(error))
      return { error: 'force-agent-mode-failed' }
    }

    let started: Awaited<ReturnType<ProjectEnvironmentJobDeps['startTurn']>>
    try {
      started = await deps.startTurn({
        prompt: buildProjectEnvironmentPrompt(input.skillName, input.skillBody),
        selection: selected.selection,
        jobId: job.jobId,
        skillName: input.skillName,
        signal: job.controller.signal,
      })
    } catch (error) {
      finishWithoutHandle(job, job.controller.signal.aborted ? 'cancelled' : 'failed', errorText(error))
      return { error: job.controller.signal.aborted ? 'job-cancelled' : 'turn-start-failed' }
    }
    if (!started.ok) {
      finishWithoutHandle(job, job.controller.signal.aborted ? 'cancelled' : 'failed', started.error)
      return { error: job.controller.signal.aborted ? 'job-cancelled' : started.error }
    }

    const attachError = attachHandle(job, started.handle)
    if (attachError) return { error: attachError }
    if (job.finishedAt !== undefined) return { error: job.error ?? 'turn-start-failed' }
    if (job.controller.signal.aborted) return { error: 'job-cancelled' }
    return {
      jobId: job.jobId,
      status: 'running',
      startedAt: job.startedAt,
      skillName: job.skillName,
      executor: {
        providerId: selected.selection.providerId,
        modelId: selected.selection.modelId,
        ...(selected.selection.reasoning ? { reasoning: selected.selection.reasoning } : {}),
      },
    }
  }

  function start(
    raw: StartProjectEnvironmentJobInput
  ): Promise<ProjectEnvironmentResult<ProjectEnvironmentJobStartResult>> {
    const checked = validateInput(raw)
    if ('error' in checked) return Promise.resolve(checked)
    const input = checked.input
    const fp = fingerprint(input)
    const cached = idempotency.get(input.idempotencyKey)
    if (cached) return cached.fingerprint === fp ? cached.result : Promise.resolve({ error: 'idempotency-conflict' })
    if (activeJob) return Promise.resolve({ error: activeJob.status === 'cancelling' ? 'job-stopping' : 'job-active' })

    // Store the promise synchronously: concurrent retries can never cross the first async preflight boundary.
    const result = doStart(input)
    idempotency.set(input.idempotencyKey, { fingerprint: fp, result })
    while (idempotency.size > IDEMPOTENCY_CACHE_LIMIT) {
      const oldest = idempotency.keys().next().value
      if (typeof oldest !== 'string') break
      idempotency.delete(oldest)
    }
    return result
  }

  async function wait(
    input: { jobId: string; waitSeconds?: number },
    signal?: AbortSignal
  ): Promise<ProjectEnvironmentResult<ProjectEnvironmentJobInfo>> {
    const job = activeJob?.jobId === input.jobId ? activeJob : jobs.get(input.jobId)
    if (!job) return { error: 'unknown-job' }
    const seconds = input.waitSeconds ?? PROJECT_ENVIRONMENT_DEFAULT_WAIT_SECONDS
    if (!Number.isInteger(seconds) || seconds < 0 || seconds > PROJECT_ENVIRONMENT_MAX_WAIT_SECONDS) {
      return { error: 'invalid-wait-seconds' }
    }
    if (job.finishedAt !== undefined || seconds === 0) return publicInfo(job)
    if (signal?.aborted) return { error: 'wait-aborted' }

    const timedOut = Symbol('timed-out')
    const aborted = Symbol('aborted')
    let timer: ReturnType<typeof setTimeout> | undefined
    let onAbort: (() => void) | undefined
    const timeout = new Promise<typeof timedOut>((resolve) => {
      timer = setTimeout(() => resolve(timedOut), seconds * 1000)
      timer.unref?.()
    })
    const abort = new Promise<typeof aborted>((resolve) => {
      if (!signal) return
      onAbort = () => resolve(aborted)
      signal.addEventListener('abort', onAbort, { once: true })
    })
    const result = await Promise.race([job.completion.then(() => undefined), timeout, abort])
    if (timer) clearTimeout(timer)
    if (onAbort) signal?.removeEventListener('abort', onAbort)
    if (result === aborted) return { error: 'wait-aborted' }
    return publicInfo(job)
  }

  function cancel(input: { jobId: string }): ProjectEnvironmentResult<ProjectEnvironmentJobInfo> {
    const job = activeJob?.jobId === input.jobId ? activeJob : jobs.get(input.jobId)
    if (!job) return { error: 'unknown-job' }
    if (job.finishedAt === undefined) dispatchCancellation(job)
    return publicInfo(job)
  }

  /** Session teardown: idempotently abort the active preflight/turn and retain its slot until terminal. */
  function stop(): ProjectEnvironmentJobInfo | null {
    if (!activeJob) return null
    dispatchCancellation(activeJob)
    return publicInfo(activeJob)
  }

  return {
    start,
    wait,
    cancel,
    stop,
    info: (): ProjectEnvironmentJobInfo | null => (activeJob ? publicInfo(activeJob) : null),
    getJob: (jobId: string): ProjectEnvironmentJobInfo | null => {
      const job = activeJob?.jobId === jobId ? activeJob : jobs.get(jobId)
      return job ? publicInfo(job) : null
    },
  }
}

export type ProjectEnvironmentJobController = ReturnType<typeof createProjectEnvironmentJobController>
