/**
 * electron-builder afterPack gate for the lean core, plus the Linux AppImage wrapper.
 * Large provider runtimes are installed on demand and must never leak into a package.
 */
import { createReadStream, existsSync, statSync } from 'node:fs'
import { chmod, readFile, readdir, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { createHash } from 'node:crypto'
import { listPackage } from '@electron/asar'

export const FORBIDDEN_RESOURCE_DIRECTORIES = ['codex', 'github-copilot', 'tunnel-client', 'local-ml-runtime']
export const REQUIRED_LEGAL_RESOURCES = [
  'LICENSE.txt',
  'THIRD_PARTY_NOTICES.md',
  'licenses/github-copilot-cli-license.txt',
  'licenses/github-copilot-runtime-NOTICE.txt',
  'licenses/github-copilot-sdk-MIT.txt',
  'licenses/openai-codex-apache-2.0.txt',
  'licenses/openai-codex-runtime-NOTICE.txt',
  'licenses/openai-codex-runtime-apache-2.0.txt',
]

const PLATFORM_PACKAGES = [
  /^@github\/copilot-(darwin|linux|linuxmusl|win32)-(arm64|x64)$/,
  /^@openai\/codex-(darwin|linux|win32)-(arm64|x64)$/,
  /^@anthropic-ai\/claude-agent-sdk-(darwin|linux|win32)-(arm64|x64)(?:-musl)?$/,
  /^@koromix\/koffi-(darwin|linux|win32)-(arm64|x64)$/,
]
const ML_PACKAGES = [/^@xenova\/transformers$/, /^@huggingface\/jinja$/, /^onnxruntime-(?:node|common|web)$/, /^sharp$/]

const expectedPlatform = (name) => (name === 'mac' ? 'darwin' : name === 'win' ? 'win32' : name)
const builderArchNames = { 0: 'ia32', 1: 'x64', 2: 'armv7l', 3: 'arm64', 4: 'universal' }

function packageNameFromEntry(entry) {
  const normalized = entry.replaceAll('\\', '/').replace(/^\/+/, '')
  const marker = 'node_modules/'
  const offset = normalized.indexOf(marker)
  if (offset < 0) return null
  const parts = normalized.slice(offset + marker.length).split('/')
  return parts[0]?.startsWith('@') ? `${parts[0]}/${parts[1] ?? ''}` : parts[0]
}

async function walkPackageNames(dir, names) {
  if (!existsSync(dir)) return
  const visit = async (current) => {
    for (const entry of await readdir(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name)
      const packageName = packageNameFromEntry(path.relative(dir, full))
      if (packageName) names.add(packageName)
      if (entry.isDirectory()) await visit(full)
    }
  }
  await visit(dir)
}

export async function findLeanCoreLeaks(resources, platform, arch) {
  const leaks = []
  for (const name of FORBIDDEN_RESOURCE_DIRECTORIES) {
    const candidate = path.join(resources, name)
    if (existsSync(candidate)) leaks.push(`Resources/${name}`)
  }

  const packageNames = new Set()
  const asar = path.join(resources, 'app.asar')
  if (existsSync(asar)) {
    for (const entry of listPackage(asar)) {
      const name = packageNameFromEntry(entry)
      if (name) packageNames.add(name)
    }
  }
  await walkPackageNames(path.join(resources, 'app.asar.unpacked'), packageNames)

  for (const name of packageNames) {
    if (ML_PACKAGES.some((pattern) => pattern.test(name))) leaks.push(`local ML package ${name}`)
  }

  const expectedOs = expectedPlatform(platform)
  for (const name of packageNames) {
    for (const pattern of PLATFORM_PACKAGES) {
      const match = pattern.exec(name)
      const packageOs = match?.[1] === 'linuxmusl' ? 'linux' : match?.[1]
      if (match && (packageOs !== expectedOs || match[2] !== arch)) leaks.push(`foreign optional package ${name}`)
    }
  }

  // More than one package in the same platform family means duplicate native payloads.
  for (const pattern of PLATFORM_PACKAGES) {
    const matches = [...packageNames].filter((name) => pattern.test(name))
    if (matches.length > 1) leaks.push(`duplicate optional packages ${matches.sort().join(', ')}`)
  }
  return [...new Set(leaks)]
}

export function missingLegalResources(resources) {
  return REQUIRED_LEGAL_RESOURCES.filter((relative) => {
    const candidate = path.join(resources, ...relative.split('/'))
    return !existsSync(candidate) || !statSync(candidate).isFile() || statSync(candidate).size === 0
  })
}

const wrapper = (bin) => `#!/bin/bash
# Wrapper generated by scripts/after-pack.mjs. Do not edit in the package.
HERE="$(dirname "$(readlink -f "$0")")"
if [ -n "$APPIMAGE" ] ; then
  exec "$HERE/${bin}" --no-sandbox "$@"
fi
exec "$HERE/${bin}" "$@"
`

export default async function afterPack(context) {
  const platform =
    context.electronPlatformName === 'darwin'
      ? 'mac'
      : context.electronPlatformName === 'win32'
        ? 'win'
        : context.electronPlatformName
  const arch = builderArchNames[context.arch]
  const resources =
    platform === 'mac'
      ? path.join(context.appOutDir, `${context.packager.appInfo.productFilename}.app`, 'Contents', 'Resources')
      : path.join(context.appOutDir, 'resources')
  const leaks = await findLeanCoreLeaks(resources, platform, arch)
  if (leaks.length > 0) throw new Error(`[after-pack] lean-core leakage:\n- ${leaks.join('\n- ')}`)
  console.log('[after-pack] lean-core leakage gate ok')

  const missingLegal = missingLegalResources(resources)
  if (missingLegal.length > 0) {
    throw new Error(`[after-pack] missing legal resources:\n- ${missingLegal.join('\n- ')}`)
  }
  console.log('[after-pack] legal resources verified')

  const manifest = JSON.parse(
    await readFile(new URL('../apps/desktop/runtime-assets/local-ml/manifest.json', import.meta.url), 'utf8')
  )
  const target = `${platform}-${arch}`
  const expected = manifest.targets[target]
  if (!expected) throw new Error(`[after-pack] Missing local ML manifest for ${target}`)
  const archiveName = `local-ml-runtime-${manifest.version}-${target}.tar.gz`
  const localMl = path.join(resources, 'local-ml')
  const bundled = await readdir(localMl)
  if (bundled.length !== 1 || bundled[0] !== archiveName) {
    throw new Error(`[after-pack] Expected exactly one local ML archive for ${target}`)
  }
  const hash = createHash('sha256')
  let bytes = 0
  for await (const chunk of createReadStream(path.join(localMl, archiveName))) {
    hash.update(chunk)
    bytes += chunk.length
  }
  if (bytes !== expected.archiveBytes || hash.digest('hex') !== expected.sha256) {
    throw new Error('[after-pack] Bundled local ML archive failed integrity verification')
  }
  console.log(`[after-pack] Bundled local ML archive verified (${target})`)

  if (platform !== 'linux') return
  const exe = context.packager.executableName
  const exePath = path.join(context.appOutDir, exe)
  const realPath = path.join(context.appOutDir, `${exe}.bin`)
  if (existsSync(realPath)) return
  await rename(exePath, realPath)
  await writeFile(exePath, wrapper(`${exe}.bin`))
  await chmod(exePath, 0o755)
}
