/**
 * The copy the shared chat components need, read from the desktop catalogues. The shared package
 * never imports react-i18next: it receives plain strings, so the two applications can keep
 * different catalogues while rendering the same components.
 */
import type { ChatUiLabels } from '@maestrly/chat-ui'
import { i18n } from './i18n'

export function chatUiLabels(): ChatUiLabels {
  const t = (key: string, options?: Record<string, unknown>) => i18n.t(key, options) as string
  return {
    copy: t('chat:messages.copy'),
    copied: t('chat:messages.copied'),
    responseDuration: (seconds) => t('chat:messages.responseTime', { duration: `${seconds}s` }),
    tool: {
      running: t('chat:tool.running'),
      done: t('chat:tool.completed'),
      error: t('chat:tool.error'),
      output: t('chat:tool.result'),
      command: t('chat:tool.arguments'),
      changes: t('ui:chatUi.changes'),
      pending: t('chat:tool.preparing'),
      awaitingPermission: t('chat:tool.awaitingPermission'),
      denied: t('chat:tool.denied'),
      imageOutput: t('chat:tool.imageOutput'),
      imageLoading: t('chat:tool.imageLoading'),
      imageUnavailable: t('chat:tool.imageUnavailable'),
    },
    context: {
      title: t('chat:meter.limitTitle'),
      used: (used, limit) => t('ui:chatUi.contextUsed', { used, limit }),
      cost: (cost) => t('ui:chatUi.contextCost', { cost }),
      unknownWindow: t('chat:meter.limitCeilingUnknown'),
    },
    composer: {
      placeholder: t('chat:composer.placeholder'),
      message: t('chat:composer.placeholder'),
      send: t('chat:composer.send'),
      stop: t('chat:composer.stop'),
      stopping: t('ui:chatUi.stopping'),
      attach: t('chat:plusMenu.imageFile'),
      add: t('chat:plusMenu.add'),
      attachments: t('chat:plusMenu.imageFile'),
      removeAttachment: t('chat:composer.remove'),
      commands: t('ui:chatUi.commands'),
      skills: t('chat:skillsMenu.button'),
      noCommands: t('ui:chatUi.noCommands'),
    },
    model: { title: t('chat:modelChip.choosePlaceholder'), effort: t('chat:reasoning.buttonTitle') },
    permission: {
      ask: t('chat:perm.askLabel'),
      full: t('chat:perm.fullLabel'),
      askHint: t('chat:perm.askDesc'),
      fullHint: t('chat:perm.fullDesc'),
    },
    usage: {
      title: t('ui:usage.heading'),
      description: t('ui:usage.desc'),
      period: t('ui:chatUi.period'),
      model: t('ui:usage.colModel'),
      input: t('ui:usage.colInput'),
      output: t('ui:usage.colOutput'),
      cached: t('ui:usage.colCacheRead'),
      turns: t('ui:usage.cardTurns'),
      cost: t('ui:usage.colCost'),
      empty: t('ui:usage.empty'),
      loading: t('ui:usage.loading'),
      refresh: t('ui:usage.refresh'),
      close: t('ui:common.close'),
      periodToday: t('ui:usage.periodToday'),
      period7d: t('ui:usage.period7d'),
      period30d: t('ui:usage.period30d'),
      period90d: t('ui:usage.period90d'),
      periodCustom: t('ui:usage.periodCustom'),
      from: t('ui:usage.from'),
      to: t('ui:usage.to'),
      cardTotalTokens: t('ui:usage.cardTotalTokens'),
      cardTotalCost: t('ui:usage.cardTotalCost'),
      cardTurns: t('ui:usage.cardTurns'),
      cardModels: t('ui:usage.cardModels'),
      colModel: t('ui:usage.colModel'),
      colInput: t('ui:usage.colInput'),
      colOutput: t('ui:usage.colOutput'),
      colCacheCreate: t('ui:usage.colCacheCreate'),
      colCacheRead: t('ui:usage.colCacheRead'),
      colTotal: t('ui:usage.colTotal'),
      colShare: t('ui:usage.colShare'),
      colCost: t('ui:usage.colCost'),
      turnsUnit: t('ui:usage.turnsUnit'),
      totalRow: t('ui:usage.totalRow'),
      unpriced: (count) => t('ui:usage.unpricedSuffix', { count }),
      noPricing: t('ui:usage.noPricing'),
      note: t('ui:usage.note'),
      dash: t('ui:common.dash'),
    },
    mermaid: {
      failed: t('ui:chatUi.invalidDiagram'),
      rendering: t('ui:notesEditor.renderingDiagram'),
      expand: t('ui:mermaid.expand'),
      zoomIn: t('ui:mermaid.zoomIn'),
      zoomOut: t('ui:mermaid.zoomOut'),
      reset: t('ui:mermaid.reset'),
      close: t('ui:mermaid.close'),
      dialog: t('ui:notesEditor.diagramMermaid'),
    },
  }
}
